_schema: _schema
paths:
  uploads: /src/assets/images
  static:
collections_config:
  post:
    path: src/content/post
    name: Post
    icon: event_available
    url: /[slug]/
    disable_url: false
    description: ''
    _editables:
      content:
        allow_custom_markup: false
        remove_custom_markup: false
        blockquote: true
        bold: true
        bulletedlist: true
        center:
        code:
        copyformatting:
        embed:
        expandable:
        format:
        height:
        horizontalrule: true
        image: true
        image_size_attributes: true
        indent: true
        italic: true
        justify:
        left:
        link:
        mime_type:
        numberedlist: true
        outdent:
        paths:
        redo: true
        removeformat: true
        resize_style:
        right:
        snippet: true
        strike: true
        styles:
        subscript: true
        superscript: true
        table: true
        underline: true
        undo: true
        width:
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
